; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve,+disable-unpredicated-ld-st-lower < %s | FileCheck %s
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve < %s | FileCheck --check-prefix CHECK-DEFAULT %s
; RUN: llc -mtriple=aarch64-linux-gnu -mcpu=a64fx < %s | FileCheck --check-prefix CHECK-A64FX %s

define void @nxv2i64(ptr %ldptr, ptr %stptr) {
; CHECK-LABEL: nxv2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    st1d { z0.d }, p0, [x1]
; CHECK-NEXT:    ret
;
; CHECK-DEFAULT-LABEL: nxv2i64:
; CHECK-DEFAULT:       // %bb.0:
; CHECK-DEFAULT-NEXT:    ldr z0, [x0]
; CHECK-DEFAULT-NEXT:    str z0, [x1]
; CHECK-DEFAULT-NEXT:    ret
;
; CHECK-A64FX-LABEL: nxv2i64:
; CHECK-A64FX:       // %bb.0:
; CHECK-A64FX-NEXT:    ptrue p0.d
; CHECK-A64FX-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-A64FX-NEXT:    st1d { z0.d }, p0, [x1]
; CHECK-A64FX-NEXT:    ret
  %l3 = load <vscale x 2 x i64>, ptr %ldptr, align 8
  store <vscale x 2 x i64> %l3, ptr %stptr, align 8
  ret void
}
